### ISSUE TITLE
Multiple Queries When 1 Expected

### ISSUE THREAD

**Issue by austinarbor** [babyfish-ct/jimmer#298]
Hello,
I am starting to experiment with jimmer and I created an abbreviated version of the sql example:

```kotlin
@Entity
interface Book {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long

    val name: String

    @ManyToMany
    @JoinTable(
        name = "BOOK_AUTHOR_MAPPING",
        joinColumnName = "BOOK_ID",
        inverseJoinColumnName = "AUTHOR_ID"
    )
    val authors: List<Author>
}
```

```kotlin
@Entity
interface Author {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long
    val firstName: String
    val lastName: String

    @ManyToMany(mappedBy = "authors")
    val books: List<Book>
}
```

```kotlin
interface BookRepository : KRepository<Book, Long> {
    fun findByName(bookName: String): Book? {
        return sql.createQuery(Book::class) {
            where(table.name like bookName)
            select(
                table.fetchBy {
                    name()
                    authors {
                        firstName()
                        lastName()
                    }
                }
            )
        }.fetchOneOrNull()
    }
}
```

However, when I call this method, it is using two queries to fetch the data instead of a single join.

```shell
jimmer> sql: select tb_1_.ID, tb_1_.NAME from BOOK tb_1_ where tb_1_.NAME like ?, variables: [%Best%], purpose: QUERY
jimmer> sql: select tb_1_.ID, tb_1_.FIRST_NAME, tb_1_.LAST_NAME from AUTHOR tb_1_ inner join BOOK_AUTHOR_MAPPING tb_2_ on tb_1_.ID = tb_2_.AUTHOR_ID where tb_2_.BOOK_ID = ?, variables: [1], purpose: LOAD
```

Am I doing something wrong, or is there a way to force it to fetch the data using a single query with a join?

**Comment by babyfish-ct** [comment]
Hello, welcome to experience Jimmer. 

You have not done anything wrong. Unlike JPA/Hibernate, Jimmer does not have the concept of `join fetch` (this is because collection fetching would cause record duplication, which is fatal for paged queries).

Jimmer first queries the aggregate root objects, and performs paging at the SQL level *(if there is paging)*, then further queries the deeper objects based on the paged results by new SQL queries.

Don't worry about `N + 1` issues. Jimmer uses something similar to GraphQL's DataLoader to batch load associated/computed properties. Here you see `=?` because there is only one aggregate root object. If there were multiple, you would see `in(?, ?, ...?)`

In addition, I have provided Discord channels for more users from different countries (https://discord.com/channels/1016206034827743283/1154480714268540929). I don't know if the channel was created successfully (not familiar with Discord), you can try it. If this Discord channel is correct, you will be the first user there, welcome!

**Comment by babyfish-ct** [comment]
Forget one point

```
table.fetchBy {
      name()
      authors { // Please focus here
          firstName()
          lastName()
      }
  }
```

In the code, `authors` means developer requires not only aggregate-roots, but also assocated objects.

**Comment by austinarbor** [comment]
Thanks for the info! So if I understand correctly, each association included in the fetch will trigger 1 query to fetch the data needed for it?

**Comment by babyfish-ct** [comment]
Each association/calculation property.
