### ISSUE TITLE
[fr] Support self or this in DTO to create nested objects

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#465]
It would be great if I could create nested anonymous objects.
Example of possible syntax: 
```
Book {
  this {
    name
    edition
  } as info
  price
}
```

**Comment by babyfish-ct** [comment]
Currently, Jimmer is working towards 1.0.0. Many of these features are actually implemented in longer-term plans. The current priority in the Jimmer plan is more towards the qualitative change of core functions rather than the non-core functions represented by data transformation.

For example, embeddable was an experimental feature that was not heavily developed before, because the user's desire to transform data was almost limitless. Getting involved in these features too early can cause the framework to deviate from the pre-planned design plan early on.

So, unless the lack of a feature is going to be overwhelmingly difficult for you, try to refrain from it.

**Comment by babyfish-ct** [comment]
Already In plan, but not now. It is will be done when jimmer is perfectly enough, so directly close it
