### ISSUE TITLE
[fr] Add support "implement interface" syntax in DTO language

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#470]
I often have situations, when I fetch some DTO and then call several business services on fetched data.
Currently I need to convert fetched DTO to business services input formats.
If I could say to DTO "please, implement this 3 interfaces" it would greatly reduce mapping code, because all services will be able to take this DTO as is.

**Comment by babyfish-ct** [comment]
Initially, the DTO language even supported inheritance. However, there was a discussion with users in the later stage, believing that DTO is a low-value type of information, and looking for reusability in low-value information often leads to the problem of convenience in the early stage but difficult to maintain in the later stage.

As a result, all these related features were later removed and users were expected not to look for reusability in low-value information.

For this new requirement, once the interface is allowed to be implemented, it will cause many problems
- Does a super interface have a generic parameters? 
- Will multiple super interfaces be destined to fail to be implemented at the same time due to the contradiction of the constraints of the generic parameters(For example, `Comparable<A>` and `Comparable<B>` cannot be implemented at same time)? 
- Whether all their behavior are implemented by the current DTO? should super the generated DTO be abstract? 
- Whether the return type of the method in the super interface is compatible with the return type of the method in the current DTO (for example, the Super interface returns `Object` and the DTO returns `String` is compatible, but the Super interface returns `String` and the DTO returns `Date` is incompatible)?

Due to the long-term development of the compiler, there are many cases where a simple initial idea can evolve into an unacceptable huge cost in the short term, so it is very cautious about the evolution of the DTO language.

**Comment by belovaf** [comment]
I thought about something very simple. If user adds interface, just add it to DTO and add `override` keyword to corresponding properties.

I understand, that this is not a core feature.
I thought that this is relativeley easy to implement feature (because you can delegate validation to a compiler), but it greatly increases DTO flexibility.

Whith this feature I can easily reshape DTOs (with default methods and @JsonIgnore) and make many other cool things.

**Comment by belovaf** [comment]
With this feature I can implement calculated properties on DTO, fold function, etc.
In my opinion this feature is very worthwhile.

**Comment by babyfish-ct** [comment]
Java/Kotlin(Not SQL) Formula properties requires `dependencies`, like this.

```
@Formula(dependencies = ['a', 'b']
val c: String
   get() = ...blabla...
```

That means in order to calculate `c`, `a` and `b` must be fetched too. In fact, Jimmer will automatically and `a` and `b` into fetcher as implicit properties(Hidden properties) if the fetcher does not contain them.

If formula property is provided by DTO, not entity. How to implement these features?

**Comment by babyfish-ct** [comment]
Try `0.8.112` please
