### ISSUE TITLE
[bug] Delete statement by foreign_key column generates additional select

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#471]
```
@Entity
interface Book : LongId {
    @ManyToOne
    val store: BookStore?

    @IdView
    val storeId: Long?
}

interface BookStore : LongId {
    @OneToMany(mappedBy = "store")
    val books: List<Book>
}

sql.createDelete(Book::class) {
    where(table.storeId eq 1)
}.execute()
```

Jimmer log:
sql: select distinct tb_1_.ID from BOOK tb_1_ where tb_1_.STORE_ID = ?, variables: [1], purpose: DELETE
sql: delete from BOOK where ID = ?, variables: [1], purpose: DELETE

**Comment by belovaf** [comment]
The problem is coming from `MutableDeleteImpl` line 122.

Expression
```
boolean directly = table.isEmpty() && binLogOnly && (
        isDissociationDisabled ||
        sqlClient.getEntityManager().getDissociationInfo(table.getImmutableType()) == null
);
```
is erroneously evaluated to false, because `table.isEmpty()` return `false`, but should return `true`.

**Comment by babyfish-ct** [comment]
This is not a bug, because there is many-to-many association `Book.authors`, Jimmer must check whether there are some records of `BOOK_AUTHOR_MAPPING` need to be deleted.

Of course, you can apply `on delete cascade`  to `BOOK_ID` of `BOOK_AUTHOR_MAPPING` to let database handle this issue. 

If `on delete cascade`  is used, the current solution(Smarter solution will be supported in future) is `disableDissociation`

```
sql
    .createDelete(Book::class) {
        where(table.storeId eq 1)
    }
    .disableDissociation() // Here is the configuration, think nothing and directly delete rows
    .execute()
```

**Comment by babyfish-ct** [comment]
Try `0.8.113`
