### ISSUE TITLE
【fr】建议加个报错，dto语言生成的dto在controller没有加上@RequestBody注解就报错

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#542]
dto语言十分依赖jackson，如果不加@RequestBody就走不了jackson

**Comment by sunshio** [comment]
这就强制要求不能使用get了，也非常合适

**Comment by babyfish-ct** [comment]
Yes, spring mvc is very flexible, it allowed user to bind any complex object by 
[org.framework.web.method.support.HandlerMethodArgumentResolver](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/method/support/HandlerMethodArgumentResolver.html)

That means any complex object can be parsed by user's extension without `@RequestBoy`, of course, include Generated DTO type that contains `fixed` or `dynamic` properties.

If this error reporting is implemented, it will **broke existing feature of spring framework**.

Now I am synchronizing the documentation, I will tell the user what happens if the input DTO type contains some `fixed` or `dynamic` input.
