### ISSUE TITLE
[Feature Request]: Supports annotated enumeration field mapping

### ISSUE THREAD

**Issue by nanakura** [babyfish-ct/jimmer#6]
This seems a bit cumbersome

```kotlin
addScalarProvider(
    ScalarProvider.enumProviderByString(
        Gender::class.java
    ) {
        it
        .map(Gender.MALE, "M")
        .map(Gender.FEMALE, "F")
    }
)
```

**Comment by babyfish-ct** [comment]
OK, I know.

**Comment by babyfish-ct** [comment]
You can use 0.2.4.

If you cannot control the source code of scalar/enum type, still use code style.
otherwise, you can you annotation style.

If both are of are used, code configuration overrides configurations.

Annotations:
@ScalarType: For scalar types except enum
@EnumType: For enum type, if argument is NAME, can be omitted
@EnumItem: Override name or ordinal for a enum value

**Comment by nanakura** [comment]
> You can use 0.2.4.
> 
> If you cannot control the source code of scalar/enum type, still use code style. otherwise, you can you annotation style.
> 
> If both are of are used, code configuration overrides configurations.
> 
> Annotations: @ScalarType: For scalar types except enum @EnumType: For enum type, if argument is NAME, can be omitted @EnumItem: Override name or ordinal for a enum value

awesome
