### ISSUE TITLE
 在子查询中，使用limit导致生成sql中，父查询选取字段会变成 count(tb_1_.ID)

### ISSUE THREAD

**Issue by Enaium** [babyfish-ct/jimmer#99]
![](https://github.com/babyfish-ct/jimmer/assets/32991121/a75b9a22-eba2-4063-b26e-3fd71cf881d2)
![](https://github.com/babyfish-ct/jimmer/assets/32991121/2d58712a-675a-489d-ad61-bbde14e060ef)

后来换了种写法

![](https://github.com/babyfish-ct/jimmer/assets/32991121/3848d21d-f434-4d5d-9164-9bb2a67ab7f6)
![](https://github.com/babyfish-ct/jimmer/assets/32991121/fc64d720-1539-4c57-9002-d45f67f4f283)
![](https://github.com/babyfish-ct/jimmer/assets/32991121/15c14050-f30c-45da-9f27-d101998aed77)

子查询的limit生成了，分页的limit还没有生成，sql信息错位

![](https://github.com/babyfish-ct/jimmer/assets/32991121/d151f21e-f603-4823-a9fb-cb88b22b1638)

**Comment by babyfish-ct** [comment]
Try `0.6.61`

The essential reason for this BUG is that both sub query and external query are paging query.

As for the SQL misalignment mentioned later, it is not a essential problem. The fact that the BUG has occurred has caused the SQL generation process to be interrupted. Of course, it was not executed.
